import Layout from "@/components/layout/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <Layout siteContentClass="pt0 pb0" headerClass="is-transparent">
      {children}
    </Layout>
  );
}
